export type BibleBook = keyof typeof BOOK_CHAPTERS;
export type BibleTranslation = 'web' | 'lsg' | 'swa' | 'lin' | 'shi';

export const TRANSLATIONS = {
  'web': {
    id: 'web',
    name: 'World English Bible',
    language: 'English',
    apiBibleId: '9879dbb7cfe39e4d-01' // Actual API.Bible ID
  },
  'lsg': {
    id: 'lsg',
    name: 'Bible J.N. Darby (French)',
    language: 'French',
    apiBibleId: 'a93a92589195411f-01' // Actual API.Bible ID for Darby
  },
  'swa': {
    id: 'swa',
    name: 'Kiswahili Contemporary Version (Neno)',
    language: 'Swahili',
    apiBibleId: '611f8eb23aec8f13-01' // Biblica® Open Kiswahili Contemporary Version
  },
  'lin': {
    id: 'lin',
    name: 'Lingala Contemporary Bible',
    language: 'Lingala',
    apiBibleId: 'ac6b6b7cd1e93057-01' // Biblica® Open Lingala Contemporary Bible 2020
  },
  'shi': {
    id: 'shi',
    name: 'Shi Bible (Mashi)',
    language: 'Shi',
    apiBibleId: 'a7dcdbdeda5e289e-02' // Projet de Traduction Bible en mashi du Congo
  }
} as const;

// API.Bible translation mappings - using actual available Bibles
export const API_BIBLE_TRANSLATIONS: Record<string, {
  id: string;
  name: string;
  language: string;
  searchPatterns: string[];
  apiBibleId: string;
}> = {
  'web': {
    id: 'web',
    name: 'World English Bible',
    language: 'English',
    searchPatterns: ['world english', 'web'],
    apiBibleId: '9879dbb7cfe39e4d-01'
  },
  'lsg': {
    id: 'lsg',
    name: 'Bible J.N. Darby (French)',
    language: 'French',
    searchPatterns: ['darby', 'j.n. darby'],
    apiBibleId: 'a93a92589195411f-01'
  },
  'swa': {
    id: 'swa',
    name: 'Kiswahili Contemporary Version (Neno)',
    language: 'Swahili',
    searchPatterns: ['kiswahili', 'swahili', 'neno'],
    apiBibleId: '611f8eb23aec8f13-01'
  },
  'lin': {
    id: 'lin',
    name: 'Lingala Contemporary Bible',
    language: 'Lingala',
    searchPatterns: ['lingala', 'lingála'],
    apiBibleId: 'ac6b6b7cd1e93057-01'
  },
  'shi': {
    id: 'shi',
    name: 'Shi Bible (Mashi)',
    language: 'Shi',
    searchPatterns: ['shi', 'mashi'],
    apiBibleId: 'a7dcdbdeda5e289e-02'
  }
};

// Book name to API.Bible book ID mapping
export const BOOK_ID_MAPPING: Record<BibleBook, string> = {
  'Genesis': 'GEN',
  'Exodus': 'EXO',
  'Leviticus': 'LEV',
  'Numbers': 'NUM',
  'Deuteronomy': 'DEU',
  'Joshua': 'JOS',
  'Judges': 'JDG',
  'Ruth': 'RUT',
  '1 Samuel': '1SA',
  '2 Samuel': '2SA',
  '1 Kings': '1KI',
  '2 Kings': '2KI',
  '1 Chronicles': '1CH',
  '2 Chronicles': '2CH',
  'Ezra': 'EZR',
  'Nehemiah': 'NEH',
  'Esther': 'EST',
  'Job': 'JOB',
  'Psalms': 'PSA',
  'Proverbs': 'PRO',
  'Ecclesiastes': 'ECC',
  'Song of Solomon': 'SNG',
  'Isaiah': 'ISA',
  'Jeremiah': 'JER',
  'Lamentations': 'LAM',
  'Ezekiel': 'EZK',
  'Daniel': 'DAN',
  'Hosea': 'HOS',
  'Joel': 'JOL',
  'Amos': 'AMO',
  'Obadiah': 'OBA',
  'Jonah': 'JON',
  'Micah': 'MIC',
  'Nahum': 'NAM',
  'Habakkuk': 'HAB',
  'Zephaniah': 'ZEP',
  'Haggai': 'HAG',
  'Zechariah': 'ZEC',
  'Malachi': 'MAL',
  'Matthew': 'MAT',
  'Mark': 'MRK',
  'Luke': 'LUK',
  'John': 'JHN',
  'Acts': 'ACT',
  'Romans': 'ROM',
  '1 Corinthians': '1CO',
  '2 Corinthians': '2CO',
  'Galatians': 'GAL',
  'Ephesians': 'EPH',
  'Philippians': 'PHP',
  'Colossians': 'COL',
  '1 Thessalonians': '1TH',
  '2 Thessalonians': '2TH',
  '1 Timothy': '1TI',
  '2 Timothy': '2TI',
  'Titus': 'TIT',
  'Philemon': 'PHM',
  'Hebrews': 'HEB',
  'James': 'JAS',
  '1 Peter': '1PE',
  '2 Peter': '2PE',
  '1 John': '1JN',
  '2 John': '2JN',
  '3 John': '3JN',
  'Jude': 'JUD',
  'Revelation': 'REV'
};

// Reverse mapping from API.Bible book ID to book name
export const BOOK_NAME_MAPPING: Record<string, BibleBook> = Object.fromEntries(
  Object.entries(BOOK_ID_MAPPING).map(([name, id]) => [id, name as BibleBook])
) as Record<string, BibleBook>;

export const BIBLE_STRUCTURE = {
  'Old Testament': [
    'Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuteronomy',
    'Joshua', 'Judges', 'Ruth', '1 Samuel', '2 Samuel',
    '1 Kings', '2 Kings', '1 Chronicles', '2 Chronicles',
    'Ezra', 'Nehemiah', 'Esther', 'Job', 'Psalms',
    'Proverbs', 'Ecclesiastes', 'Song of Solomon', 'Isaiah',
    'Jeremiah', 'Lamentations', 'Ezekiel', 'Daniel', 'Hosea',
    'Joel', 'Amos', 'Obadiah', 'Jonah', 'Micah', 'Nahum',
    'Habakkuk', 'Zephaniah', 'Haggai', 'Zechariah', 'Malachi'
  ],
  'New Testament': [
    'Matthew', 'Mark', 'Luke', 'John', 'Acts',
    'Romans', '1 Corinthians', '2 Corinthians', 'Galatians',
    'Ephesians', 'Philippians', 'Colossians', '1 Thessalonians',
    '2 Thessalonians', '1 Timothy', '2 Timothy', 'Titus',
    'Philemon', 'Hebrews', 'James', '1 Peter', '2 Peter',
    '1 John', '2 John', '3 John', 'Jude', 'Revelation'
  ]
} as const;

// French book names mapping (for J.N. Darby translation)
export const FRENCH_BOOK_NAMES: Record<BibleBook, string> = {
  'Genesis': 'Genèse',
  'Exodus': 'Exode',
  'Leviticus': 'Lévitique',
  'Numbers': 'Nombres',
  'Deuteronomy': 'Deutéronome',
  'Joshua': 'Josué',
  'Judges': 'Juges',
  'Ruth': 'Ruth',
  '1 Samuel': '1 Samuel',
  '2 Samuel': '2 Samuel',
  '1 Kings': '1 Rois',
  '2 Kings': '2 Rois',
  '1 Chronicles': '1 Chroniques',
  '2 Chronicles': '2 Chroniques',
  'Ezra': 'Esdras',
  'Nehemiah': 'Néhémie',
  'Esther': 'Esther',
  'Job': 'Job',
  'Psalms': 'Psaumes',
  'Proverbs': 'Proverbes',
  'Ecclesiastes': 'Ecclésiaste',
  'Song of Solomon': 'Cantique des Cantiques',
  'Isaiah': 'Ésaïe',
  'Jeremiah': 'Jérémie',
  'Lamentations': 'Lamentations',
  'Ezekiel': 'Ézéchiel',
  'Daniel': 'Daniel',
  'Hosea': 'Osée',
  'Joel': 'Joël',
  'Amos': 'Amos',
  'Obadiah': 'Abdias',
  'Jonah': 'Jonas',
  'Micah': 'Michée',
  'Nahum': 'Nahum',
  'Habakkuk': 'Habacuc',
  'Zephaniah': 'Sophonie',
  'Haggai': 'Aggée',
  'Zechariah': 'Zacharie',
  'Malachi': 'Malachie',
  'Matthew': 'Matthieu',
  'Mark': 'Marc',
  'Luke': 'Luc',
  'John': 'Jean',
  'Acts': 'Actes',
  'Romans': 'Romains',
  '1 Corinthians': '1 Corinthiens',
  '2 Corinthians': '2 Corinthiens',
  'Galatians': 'Galates',
  'Ephesians': 'Éphésiens',
  'Philippians': 'Philippiens',
  'Colossians': 'Colossiens',
  '1 Thessalonians': '1 Thessaloniciens',
  '2 Thessalonians': '2 Thessaloniciens',
  '1 Timothy': '1 Timothée',
  '2 Timothy': '2 Timothée',
  'Titus': 'Tite',
  'Philemon': 'Philémon',
  'Hebrews': 'Hébreux',
  'James': 'Jacques',
  '1 Peter': '1 Pierre',
  '2 Peter': '2 Pierre',
  '1 John': '1 Jean',
  '2 John': '2 Jean',
  '3 John': '3 Jean',
  'Jude': 'Jude',
  'Revelation': 'Apocalypse'
};

// Swahili book names mapping (for Kiswahili Contemporary Version)
export const SWAHILI_BOOK_NAMES: Record<BibleBook, string> = {
  'Genesis': 'Mwanzo',
  'Exodus': 'Kutoka',
  'Leviticus': 'Mambo ya Walawi',
  'Numbers': 'Hesabu',
  'Deuteronomy': 'Kumbukumbu la Torati',
  'Joshua': 'Yoshua',
  'Judges': 'Waamuzi',
  'Ruth': 'Ruthu',
  '1 Samuel': '1 Samweli',
  '2 Samuel': '2 Samweli',
  '1 Kings': '1 Wafalme',
  '2 Kings': '2 Wafalme',
  '1 Chronicles': '1 Mambo ya Nyakati',
  '2 Chronicles': '2 Mambo ya Nyakati',
  'Ezra': 'Ezra',
  'Nehemiah': 'Nehemia',
  'Esther': 'Esta',
  'Job': 'Ayubu',
  'Psalms': 'Zaburi',
  'Proverbs': 'Mithali',
  'Ecclesiastes': 'Mhubiri',
  'Song of Solomon': 'Wimbo wa Sulemani',
  'Isaiah': 'Isaya',
  'Jeremiah': 'Yeremia',
  'Lamentations': 'Maombolezo',
  'Ezekiel': 'Ezekieli',
  'Daniel': 'Danieli',
  'Hosea': 'Hosea',
  'Joel': 'Yoeli',
  'Amos': 'Amosi',
  'Obadiah': 'Obadia',
  'Jonah': 'Yona',
  'Micah': 'Mika',
  'Nahum': 'Nahumu',
  'Habakkuk': 'Habakuki',
  'Zephaniah': 'Sefania',
  'Haggai': 'Hagai',
  'Zechariah': 'Zekaria',
  'Malachi': 'Malaki',
  'Matthew': 'Mathayo',
  'Mark': 'Marko',
  'Luke': 'Luka',
  'John': 'Yohana',
  'Acts': 'Matendo ya Mitume',
  'Romans': 'Warumi',
  '1 Corinthians': '1 Wakorintho',
  '2 Corinthians': '2 Wakorintho',
  'Galatians': 'Wagalatia',
  'Ephesians': 'Waefeso',
  'Philippians': 'Wafilipi',
  'Colossians': 'Wakolosai',
  '1 Thessalonians': '1 Wathesalonike',
  '2 Thessalonians': '2 Wathesalonike',
  '1 Timothy': '1 Timotheo',
  '2 Timothy': '2 Timotheo',
  'Titus': 'Tito',
  'Philemon': 'Filemoni',
  'Hebrews': 'Waebrania',
  'James': 'Yakobo',
  '1 Peter': '1 Petro',
  '2 Peter': '2 Petro',
  '1 John': '1 Yohana',
  '2 John': '2 Yohana',
  '3 John': '3 Yohana',
  'Jude': 'Yuda',
  'Revelation': 'Ufunuo'
};

// Lingala book names mapping (for Lingala Contemporary Bible)
export const LINGALA_BOOK_NAMES: Record<BibleBook, string> = {
  'Genesis': 'Ebandeli',
  'Exodus': 'Kobima',
  'Leviticus': 'Levitique',
  'Numbers': 'Motango',
  'Deuteronomy': 'Deuteronome',
  'Joshua': 'Jozue',
  'Judges': 'Bakambi',
  'Ruth': 'Ruti',
  '1 Samuel': '1 Samuele',
  '2 Samuel': '2 Samuele',
  '1 Kings': '1 Bakonzi',
  '2 Kings': '2 Bakonzi',
  '1 Chronicles': '1 Masolo',
  '2 Chronicles': '2 Masolo',
  'Ezra': 'Esdras',
  'Nehemiah': 'Nehemie',
  'Esther': 'Esther',
  'Job': 'Job',
  'Psalms': 'Banzembo',
  'Proverbs': 'Masese',
  'Ecclesiastes': 'Moteyi',
  'Song of Solomon': 'Nzembo ya Salomo',
  'Isaiah': 'Ezayi',
  'Jeremiah': 'Jeremi',
  'Lamentations': 'Kolela',
  'Ezekiel': 'Ezekiele',
  'Daniel': 'Daniele',
  'Hosea': 'Oze',
  'Joel': 'Joele',
  'Amos': 'Amosi',
  'Obadiah': 'Abdia',
  'Jonah': 'Jona',
  'Micah': 'Mike',
  'Nahum': 'Naumi',
  'Habakkuk': 'Abakuki',
  'Zephaniah': 'Sofoni',
  'Haggai': 'Age',
  'Zechariah': 'Zakari',
  'Malachi': 'Malaki',
  'Matthew': 'Matayo',
  'Mark': 'Marko',
  'Luke': 'Luka',
  'John': 'Yoane',
  'Acts': 'Misala ya Bantoma',
  'Romans': 'Baroma',
  '1 Corinthians': '1 Bakorinthe',
  '2 Corinthians': '2 Bakorinthe',
  'Galatians': 'Bagalati',
  'Ephesians': 'Baefeso',
  'Philippians': 'Bafilipi',
  'Colossians': 'Bakolose',
  '1 Thessalonians': '1 Batesaloniki',
  '2 Thessalonians': '2 Batesaloniki',
  '1 Timothy': '1 Timote',
  '2 Timothy': '2 Timote',
  'Titus': 'Tito',
  'Philemon': 'Filemoni',
  'Hebrews': 'Baebreu',
  'James': 'Jakobo',
  '1 Peter': '1 Petelo',
  '2 Peter': '2 Petelo',
  '1 John': '1 Yoane',
  '2 John': '2 Yoane',
  '3 John': '3 Yoane',
  'Jude': 'Juda',
  'Revelation': 'Emoniseli'
};

// Shi (Mashi) book names mapping (for Shi Bible from Congo)
export const SHI_BOOK_NAMES: Record<BibleBook, string> = {
  'Genesis': 'Murhondêro',
  'Exodus': 'Okusôka',
  'Leviticus': 'Abalevi',
  'Numbers': 'Amabalo',
  'Deuteronomy': 'Okubûza kabiri',
  'Joshua': 'Yoshua',
  'Judges': 'Abacamûzi',
  'Ruth': 'Rutu',
  '1 Samuel': '1 Samweli',
  '2 Samuel': '2 Samweli',
  '1 Kings': '1 Abami',
  '2 Kings': '2 Abami',
  '1 Chronicles': '1 Ebyafumirizibwa',
  '2 Chronicles': '2 Ebyafumirizibwa',
  'Ezra': 'Ezra',
  'Nehemiah': 'Nehemiya',
  'Esther': 'Esteri',
  'Job': 'Yobu',
  'Psalms': 'Zaburi',
  'Proverbs': 'Amafumbo',
  'Ecclesiastes': 'Omubwirizi',
  'Song of Solomon': 'Oluyimba lwa Solomoni',
  'Isaiah': 'Isaya',
  'Jeremiah': 'Yeremiya',
  'Lamentations': 'Ebikunguzi',
  'Ezekiel': 'Ezekieli',
  'Daniel': 'Danieli',
  'Hosea': 'Hoseya',
  'Joel': 'Yoeli',
  'Amos': 'Amosi',
  'Obadiah': 'Obadiya',
  'Jonah': 'Yona',
  'Micah': 'Mika',
  'Nahum': 'Nahumu',
  'Habakkuk': 'Habakuki',
  'Zephaniah': 'Sefaniya',
  'Haggai': 'Hagai',
  'Zechariah': 'Zekariya',
  'Malachi': 'Malaki',
  'Matthew': 'Matayo',
  'Mark': 'Marko',
  'Luke': 'Luka',
  'John': 'Yohana',
  'Acts': 'Ebikolwa',
  'Romans': 'Abaroma',
  '1 Corinthians': '1 Abakorintu',
  '2 Corinthians': '2 Abakorintu',
  'Galatians': 'Abagalatiya',
  'Ephesians': 'Abaefeso',
  'Philippians': 'Abafilipi',
  'Colossians': 'Abakolose',
  '1 Thessalonians': '1 Abatesalonika',
  '2 Thessalonians': '2 Abatesalonika',
  '1 Timothy': '1 Timoteo',
  '2 Timothy': '2 Timoteo',
  'Titus': 'Tito',
  'Philemon': 'Filemoni',
  'Hebrews': 'Abaebraniya',
  'James': 'Yakobo',
  '1 Peter': '1 Petero',
  '2 Peter': '2 Petero',
  '1 John': '1 Yohana',
  '2 John': '2 Yohana',
  '3 John': '3 Yohana',
  'Jude': 'Yuda',
  'Revelation': 'Okubikûlwa'
};

// Helper function to get localized book name
export function getLocalizedBookName(book: BibleBook, translation: BibleTranslation): string {
  switch (translation) {
    case 'lsg':
      return FRENCH_BOOK_NAMES[book] || book;
    case 'swa':
      return SWAHILI_BOOK_NAMES[book] || book;
    case 'lin':
      return LINGALA_BOOK_NAMES[book] || book;
    case 'shi':
      return SHI_BOOK_NAMES[book] || book;
    default:
      return book;
  }
}

export const BOOK_CHAPTERS = {
  // Old Testament
  'Genesis': 50,
  'Exodus': 40,
  'Leviticus': 27,
  'Numbers': 36,
  'Deuteronomy': 34,
  'Joshua': 24,
  'Judges': 21,
  'Ruth': 4,
  '1 Samuel': 31,
  '2 Samuel': 24,
  '1 Kings': 22,
  '2 Kings': 25,
  '1 Chronicles': 29,
  '2 Chronicles': 36,
  'Ezra': 10,
  'Nehemiah': 13,
  'Esther': 10,
  'Job': 42,
  'Psalms': 150,
  'Proverbs': 31,
  'Ecclesiastes': 12,
  'Song of Solomon': 8,
  'Isaiah': 66,
  'Jeremiah': 52,
  'Lamentations': 5,
  'Ezekiel': 48,
  'Daniel': 12,
  'Hosea': 14,
  'Joel': 3,
  'Amos': 9,
  'Obadiah': 1,
  'Jonah': 4,
  'Micah': 7,
  'Nahum': 3,
  'Habakkuk': 3,
  'Zephaniah': 3,
  'Haggai': 2,
  'Zechariah': 14,
  'Malachi': 4,
  
  // New Testament
  'Matthew': 28,
  'Mark': 16,
  'Luke': 24,
  'John': 21,
  'Acts': 28,
  'Romans': 16,
  '1 Corinthians': 16,
  '2 Corinthians': 13,
  'Galatians': 6,
  'Ephesians': 6,
  'Philippians': 4,
  'Colossians': 4,
  '1 Thessalonians': 5,
  '2 Thessalonians': 3,
  '1 Timothy': 6,
  '2 Timothy': 4,
  'Titus': 3,
  'Philemon': 1,
  'Hebrews': 13,
  'James': 5,
  '1 Peter': 5,
  '2 Peter': 3,
  '1 John': 5,
  '2 John': 1,
  '3 John': 1,
  'Jude': 1,
  'Revelation': 22
} as const; 